name: VoidWorldGenerator
version: 1.0.0
main: fr.formiko.voidworldgenerator.VoidWorldGenerator
description: Generate empty world
author: Hydrolien
website: https://github.com/HydrolienF/VoidWorldGenerator
api-version: '1.20'
folia-supported: true
load: STARTUP